FROM node:16-alpine

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    && rm -rf /var/cache/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

WORKDIR /app

COPY . .

RUN npm install \
    && npm i puppeteer

CMD ["sh", "-c", "npm run dev"]

EXPOSE 3001

ENV TZ=Asia/Shanghai
